### ISSUE TITLE
[主頁][新增][附近熱門] 選擇分類後，列出空白項目

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#218] opened 2015-05-11 15:32 UTC
![2015-05-10-23-42-02](https://cloud.githubusercontent.com/assets/10726049/7568563/138dd146-f836-11e4-98cc-c032be44992f.png)

**Comment by cmacma7** [comment] 2015-05-26 11:58
Fixed in 1.1.728. Caused by not handle row[0].length==0 problem.

**Closed as completed** 2015-06-02 15:44 UTC
Labels: Fixed
