### ISSUE TITLE
Jump to station or store 造成原本頁面轉圈圈

### ISSUE THREAD

**Issue by cyen1121** [cmacma7/bn#63] opened 2015-01-28 10:08 UTC
handleWatchStation()

**Comment by cmacma7** [comment] 2015-01-30 14:46
Hi David, can you describe more?

**Comment by cmacma7** [comment] 2015-01-31 02:19
Hi David, cannot reproduce, so I need your help for the detailed description.

**Comment by cyen1121** [comment] 2015-01-31 16:32
我使用Mac 的 Chrome然後去store的春水堂-->全國據點-->第一個widget有前往(go store)一跳頁整頁就會開另一個新頁，再回來原本的頁面就會看到jquery mobile  的loading再轉然後station 裡面沒有半個widgets

**Comment by cmacma7** [comment] 2015-02-09 14:53
Hi David, please help to add this condition to bn.tagfans.com, we cannot debug on store.tagfans.com...

**Comment by cmacma7** [comment] 2015-02-09 14:58
Please see http://bn.tagfans.com/public/jqm.html#page_join?id=162&viewType=station  the second widget that jump without create another page. Working fine in this condition.

**Comment by cyen1121** [comment] 2015-02-10 10:34
只有Store --> station -->前往 才會發生
直接透過List --> station 正常

**Comment by cmacma8** [comment] 2015-02-10 14:01
Cause by a workaround that will show circle when the platform is not win32. But since open store inside a store does not need to show circle then redirect, so fix by check whether it is store inside store.
Fix in SVN 615. Fixed in store and bn .tagfans.com

**Closed as completed by cmacma8** 2015-02-10 14:01 UTC
