### ISSUE TITLE
Evelyn反應應該被取消或修正的訂單，在新單被刪除之後，又出現了

### ISSUE THREAD

**Issue by peichingliao** [cmacma7/bn#861] opened 2016-10-28 06:07 UTC
ex: 00085 --> 修改訂單為 00087
00087被刪除，並clean cache之後，00085卻出現了！

**Comment by cmacma7** [comment] 2016-10-31 01:11
This is caused by FB Scan use deleteNoteId to delete erased orders. When user delete the last order, the last deleteNoteId will not execute if user clean the cache, so we will see previous order.
Fix by issue another order with nid=0 and deleteNoteId the last order.

**Comment by cmacma7** [comment] 2016-10-31 01:12
Fixed on BN.

**Comment by Iris926** [comment] 2016-11-18 05:57
[Test Site] store
[Version] v1.1.1549.1
[Result] Fixed

**Closed as completed by Iris926** 2016-11-18 05:57 UTC
Labels: bug, Fixed, 團購
