### ISSUE TITLE
[直接複製網址列] 未登入狀態點商品連結，系統要求登入後，無法跳轉回原商品

### ISSUE THREAD

**Issue by kevinyu75** [cmacma7/bn#913] opened 2016-11-05 11:22 UTC
發生位置: 新版tagging system  商店之商品。
http://store.tagfans.com/index.html#page_join?o=3797&tag=promote,%E6%8E%A8%E8%96%A6%E5%95%86%E5%93%81&viewType=station&mode=ec&fullscreen=939725

**Comment by cmacma7** [comment] 2016-11-06 23:15
Only happen in product page mode.

**Comment by cmacma7** [comment] 2016-11-07 02:39
Fixed on bn and store.tagfans.com/debug at version 1486.1

**Comment by Iris926** [comment] 2016-11-07 03:38
[Version] v1.1.1486
[Test Site] store.tagfans.com/debug/
[Scenario] 
1. 未登入FB帳號的客人/進商店&進入fb only商品頁 http://store.tagfans.com/debug/#page_join?o=3722&id=20618&viewType=station&srcNoteId=868385&fullscreen=1024055
2. 輸入商品數量/popup請登入真實帳戶/登入

[Result] 導至該商品分類 http://store.tagfans.com/debug/#page_join?o=3722&id=20618&viewType=station&srcNoteId=868385&fullscreen=1024055

[Expected Result] 登入後，應直接到該商品頁

**Comment by Iris926** [comment] 2016-12-13 09:56
[Version] v1.1.1637
[Test Site] store
[Scenario & Result] 請參考附圖
![image](https://cloud.githubusercontent.com/assets/22789907/21135616/6c6fd6aa-c15d-11e6-98d8-77baf72d78b9.png)

**Comment by cmacma7** [comment] 2016-12-14 01:42
This is not a product share link. This is the link directly copy from URL.
In EC mode, we cannot support direct copy link, you need to use share button to copy the share link.

**Comment by cmacma7** [comment] 2016-12-21 06:07
fix at store/debug 1705.8. Problem caused by product widget toggle fullscreen mode, and because of the "fullscreen" parameter in the url, cause toggleFullscreen issue back(). Solved by filter out "fullscreen" parameter in the url by replaceState.

**Comment by Iris926** [comment] 2016-12-23 09:45
refer to #1117

**Closed as completed by Iris926** 2016-12-23 09:45 UTC
Labels: bug, Fixed, First Priority, 團購
