### ISSUE TITLE
[Widget][互動&即時服務][1.1.711] Bug

### ISSUE THREAD

**Issue by gameflierHao** [cmacma7/bn#234] opened 2015-05-15 07:08 UTC
1. 建立菜單
   a. 店家收到通知內容 order data
   b. 等候時間範圍，輸入非數字會導致顯示錯誤．
2. 預約訂位系統
   a. 店家收到通知內容 order data
   b. 客戶收到訂單狀態改變的推播，點擊推播後導到訊息頁，卻無訂單相關內容．
   c. 顧客在不同裝置上,訂單狀態不會sync．
   ![image1](https://cloud.githubusercontent.com/assets/1106733/7648274/cd2282f2-fb13-11e4-9bea-eec678302789.JPG)
   ![imag2e1](https://cloud.githubusercontent.com/assets/1106733/7648334/6ba272b6-fb14-11e4-9091-5d66e259ce71.JPG)
3. 客戶滿意度調查表
   a. 店家收到通知內容 order data
   b. 滿意度調查表可以重複發送,不同裝置同帳號填選問券時不會sync．
4. 單一商品訂購
   a. 店家收到通知內容 order data
   b. 顧客在不同裝置上,訂單狀態不會sync．
   ![image1](https://cloud.githubusercontent.com/assets/1106733/7648274/cd2282f2-fb13-11e4-9bea-eec678302789.JPG)
   ![image2](https://cloud.githubusercontent.com/assets/1106733/7648278/d549a474-fb13-11e4-80cf-98e50ecc6693.JPG)

**Comment by cyen1121** [comment] 2015-05-16 06:06
c 不做變動
a 修正了
b 系統那邊需要做調整

**Comment by cmacma7** [comment] 2015-05-16 14:18
B is not a bug. It is not "not sync", it is user need to open history to see the new state.
Each order in every device will only remember its state of each device, otherwise if device A and device B login into the same account, but put order to the same widget (both device A and device B put order), which one should be sync? As the result, there is no need to sync.

**Comment by cmacma7** [comment] 2015-05-16 14:19
Separate the bug to another one in order to close this item

**Comment by cmacma7** [comment] 2015-05-16 14:20
Fixed, assign to reporter.

**Closed as completed** 2015-05-25 09:20 UTC
Labels: Fixed
